#!/usr/bin/env python3
"""
Module Data Builder for FreeOSINT

This script reads all the module JSON files in the modules directory
and generates a modules-data.js file that can be used by the website
when running without a server.

Usage:
    python build-modules-data.py

The script will:
1. Read all JSON files in the modules directory
2. Generate a modules-data.js file with all the module data
3. Place the file in the js directory
"""

import os
import json
import glob

def main():
    print("Building modules-data.js...")
    
    # Get the directory of this script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Paths
    modules_dir = os.path.join(script_dir, 'modules')
    output_file = os.path.join(script_dir, 'js', 'modules-data.js')
    
    # Initialize the data structure
    modules_data = {
        'index': [],
        'modules': {}
    }
    
    # Read the index.json file
    index_path = os.path.join(modules_dir, 'index.json')
    if os.path.exists(index_path):
        with open(index_path, 'r', encoding='utf-8') as f:
            modules_data['index'] = json.load(f)
        print(f"Loaded index with {len(modules_data['index'])} modules")
    else:
        print("Warning: index.json not found")
    
    # Read all other JSON files in the modules directory
    module_files = glob.glob(os.path.join(modules_dir, '*.json'))
    for file_path in module_files:
        filename = os.path.basename(file_path)
        if filename == 'index.json':
            continue  # Skip the index file, we already processed it
        
        module_id = filename.replace('.json', '')
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                module_data = json.load(f)
                modules_data['modules'][module_id] = module_data
                print(f"Loaded module: {module_id}")
        except json.JSONDecodeError as e:
            print(f"Error parsing {filename}: {e}")
        except Exception as e:
            print(f"Error loading {filename}: {e}")
    
    # Generate the JavaScript file
    js_content = """/**
 * Modules Data for FreeOSINT.org
 * This file is automatically generated from the JSON files in the modules directory.
 * Do not edit this file directly, edit the JSON files instead.
 * 
 * Generated on: {timestamp}
 */

// Define the modules data
const MODULES_DATA = {json_data};

console.log('Modules data loaded successfully: {module_count} modules');
""".format(
        timestamp=__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        json_data=json.dumps(modules_data, indent=2),
        module_count=len(modules_data['modules'])
    )
    
    # Write the JavaScript file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"Successfully generated {output_file} with {len(modules_data['modules'])} modules")

if __name__ == "__main__":
    main()